# Generated by Django 3.2.4 on 2021-12-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='roll_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
