# Generated by Django 4.0 on 2022-01-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_person_roll_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
